SET SERVEROUTPUT ON;
SET VERIFY OFF;


CREATE OR REPLACE TRIGGER PRODUCT_ADDED_TO_ORDER
AFTER INSERT
ON ORDER_PRODUCT
FOR EACH ROW
DECLARE
	product_name product_view.product_name%TYPE;
BEGIN
	DBMS_OUTPUT.PUT_LINE('PRODUCT ID ADDED TO ORDER.');
END;
/



